#!/bin/sh

cpu=`cat /proc/cpuinfo  | grep "model name" | cut -d: -f2- | cut -d" " -f2-`
mhz=`cat /proc/cpuinfo  | grep "cpu MHz"    | cut -d: -f2- | cut -d" " -f2-`
mem=`free | grep Mem | awk {'print $2'}`

# create a fresh issue file
cat << EOF > /System/Settings/issue
[36;1mWelcome to `cat /System/Settings/GoboLinuxVersion`.

[36;22mSystem........:[34;1m `uname -srm`
[36;22mProcessor.....:[34;1m $cpu CPU $mhz MHz
[36;22mMemory........:[34;1m $mem
[0m[36;22mTerminal......: [34;1m\l
[33;1m
EOF
