#!/bin/sh

source /System/Settings/NetworkSettings

case "$1" in
    [sS]tart)
        for i in $NetworkInterfacesOnBoot
        do
            ipaddr=`eval 'echo $'$i'_IP'`
            netmask=`eval 'echo $'$i'_Netmask'`
            
            if [ -z "$ipaddr" ]
            then
                # launch dhcp daemon
                [ -x /bin/dhcpcd ] && dhcpcd $i || udhcpc -b -q -i $i -s /System/Settings/udhcpc.script
            else
                # launch interface by ifconfig
                [ ! -z "$netmask" ] && netmask="netmask $netmask"
                ifconfig "$i" "$ipaddr" "$netmask"
            fi
        done
        [ "$Gateway" ] && route add default gw $Gateway dev $GatewayInterface 2> /dev/null
        ;;
    [sS]top)
        for i in $NetworkInterfacesOnBoot
        do
            ifconfig $i down
        done
        [ "$Gateway" ] && route del default gw $Gateway dev $GatewayInterface 2> /dev/null
        ;;
    [rR]estart)
        $0 stop
        $0 start
        ;;
esac
