#!/bin/sh

source /System/Settings/NetworkSettings

case "$1" in
    [sS]tart)
        for i in $network_interfaces
        do
            ipaddr=`eval 'echo $'$i'_IP'`
            netmask=`eval 'echo $'$i'_Netmask'`
            
            if [ -z "$ipaddr" ]
            then
                # launch dhcp daemon
                [ -x /bin/dhcpcd ] && dhcpcd $i || udhcpc -b -q -i $i
            else
                # launch interface by ifconfig
                [ ! -z "$netmask" ] && netmask="netmask $netmask"
                ifconfig "$i" "$ipaddr" "$netmask"
            fi
        done
        route add default gw $Gateway dev $GatewayInterface 2> /dev/null
        ;;
    [sS]top)
        for i in $network_interfaces
        do
            ifconfig $i down
        done
        route del default gw $gateway dev $gateway_interface 2> /dev/null
        ;;
esac
