#!/bin/sh

mount -n -t proc  none /System/Kernel/Status
mount -n -t sysfs none /System/Kernel/Objects
mount -n -t tmpfs none /System/Kernel/Devices

/sbin/mdev -s
mkdir /System/Kernel/Devices/pts
mkdir /System/Kernel/Devices/shm

# since mdev doesn't handle sub-directories, create some symlinks here
ln -s /System/Kernel/Devices /System/Kernel/Devices/snd
ln -s /System/Kernel/Devices /System/Kernel/Devices/input
ln -s /System/Kernel/Devices /System/Kernel/Devices/net

echo /bin/mdev > /System/Kernel/Status/sys/kernel/hotplug
