#!/bin/bash

manifest_do_install() {
   for i in "${manifest[@]}"
   do
      src=`echo $i | cut -d: -f1`
      dst=`echo $i | cut -d: -f2-`
      if [ $(basename $(pwd)) != $(basename "${dir}") ]
      then
         fullsrc="${dir}/${src}"
      else
         fullsrc="${src}"
      fi
      fulldst="${installprefix}/${dst}"
      mkdir -p $(dirname "$fulldst")
      if Ends_With "/" "$fulldst"
      then
         mkdir -p "$fulldst"
      fi
      Log_Normal "Installing ${fullsrc} into ${fulldst}"
      if [ -d "${fullsrc}" -a -d "${fulldst}" ]
      then cp -Rv --no-preserve=ownership "${fullsrc}"/* "${fulldst}"
      else cp -Rv --no-preserve=ownership ${fullsrc} "${fulldst}"
      fi
   done
}
