#!/bin/bash
scons_sane_check() {
   Quiet scons --version || Die "This is a scons type recipe and you don't seem to have scons installed."
}

scons_init() {
   create_dirs_first="yes"
   scons="scons"
}

scons_do_build() {
   if [ ! "$override_default_options" = "yes" ]
   then
      scons_variables=(
         "${scons_variables[@]}"
         "PREFIX=$target"
         "prefix=$target"
      )
   fi
   Add_Use_Flags_Options_To_Array scons_variables

   scons_variables=(`echo ${scons_variables[@]} | sed "s,$target,$goboIndex,g"`)
   $scons "${scons_variables[@]}" "${build_variables[@]}" $build_target || wrap_fail "Build failed."
}

scons_do_install() {
   SandboxInstall $verbose ${unmanagedlist:+--unmanaged-files "${unmanagedlist}"} ${sandboxopts:+"${sandboxopts[@]}"} -c $scons "$appname" "$versionnumber" -- "${scons_variables[@]}" "${install_variables[@]}" $install_target || wrap_fail "Installation failed"
}
