#!/bin/bash

manifest_do_install() {
   for i in "${manifest[@]}"
   do
      src=`echo $i | cut -d: -f1`
      dst=`echo $i | cut -d: -f2-`
      fullsrc="${dir}/${src}"
      fulldst="${installprefix}/${dst}"
      $sudo_exec mkdir -p $(dirname "$fulldst")
      if Ends_With "/" "$fulldst"
      then
         $sudo_exec mkdir -p "$fulldst"
      fi
      Log_Normal "Installing ${fullsrc} into ${fulldst}"
      if [ -d "${fullsrc}" -a -d "${fulldst}" ]
      then $sudo_exec cp -Rv --no-preserve=ownership "${fullsrc}"/* "${fulldst}"
      else $sudo_exec cp -Rv --no-preserve=ownership ${fullsrc} "${fulldst}"
      fi
   done
}
