#!/bin/sh
Exec "Remounting root file system..."          mount -n -o remount,rw /
Exec "Cleaning mtab and boot settings..."      rm -f "$goboSettings/mtab"*
Exec "Cleaning up any stale lock files..."     eval "find $goboVariable/{run,lock}/ -type f | grep -v utmp | xargs -i rm -rf {}; rm -rf  $goboTemp/.X*-lock"
Exec "Mounting system filesystems..."          mount -a -t sysfs
Exec "Starting Udev..."                        Udev Start

#Daemon                                        /System/Links/Executables/sshd -D
Daemon                                        klogd -n
Daemon                                        syslogd -n -m 0

Exec "Checking remaining file systems..."     fsck -p -C -T -A -R
Exec "Hiding legacy tree..."                  GoboHide Start
Exec "Setting clock..."                       SetClock Start
Exec "Creating new mtab..."                   mount -o remount,rw /
Exec "Mounting remaining file systems..."     mount -a -t nonfs,nosmbfs,noproc,noswap,nodevpts
Exec "Activating all swap files/partitions..." swapon -a
Exec "Linking kernel modules directory..."    ln -nfs "$goboModules"/`uname -r` "$goboLibraries"/modules/`uname -r`
Exec "Setting hostname to $HostName..."       hostname "$HostName"

[ "${UserDefinedModules[*]}" ] && \
Exec "Loading user-defined kernel modules..." LoadModules

Exec "Creating utmp and wtmp..."              CreateChmod 644 $goboVariable/{run/utmp,log/wtmp}
Exec "Removing one-time boot settings..."     rm -f $goboSettings/nologin /fastboot /forcefsck

#Exec "Starting PCMCIA daemon..."             PCMCIA Start
Exec "Initializing network..."                Network Start
#Exec "Loading sound settings..."              Alsactl Start
Exec "Starting message bus..."                MessageBus Start
Exec "Starting hardware abstraction layer..." HAL Start
Exec "Loading keymap..."                      loadkeys "$KeymapLayout"
