#!/bin/sh

#Exec "Stopping mouse driver"                 Mouse Stop
#Exec "Storing sound settings"                 Alsactl Stop
Exec "Saving system time"                     SetClock Stop
Exec "Stopping kernel log daemon"            killall klogd
Exec "Stopping system log daemon"            killall syslogd
Exec "Unmounting network file systems"        umount -a -r -t nfs,smbfs,cifs
Exec "Stopping network"                       Network Stop "$NetworkInterfaces"
Exec "Sending all processes the TERM signal"  killall5 -15
usleep 500000
Exec "Sending all processes the KILL signal"  killall5 -9
Exec "Removing login records"                 rm -f ${goboVariable}/run/utmp
Exec "Deactivating all swap files/partitions" swapoff -a
Exec "Unmounting all other file systems"      umount -a -r
#Exec "Stopping PCMCIA daemon"                PCMCIA Stop
