#!/bin/sh

export PATH=/System/Links/Executables:/System/Links/Tasks
export LD_LIBRARY_PATH=/System/Links/Libraries

echo "Mounting file system read-write..."; mount -o remount,rw /
echo "Mounting remaining filesystems...";  mount -a
echo "Loading udev task...";               Udev start
echo "Hiding the legacy tree...";          GoboHide start
echo "Loading network settings...";        Network start
echo "Loading mouse driver...";            Mouse start
echo "Loading SSH daemon...";              /Programs/OpenSSH/Current/sbin/sshd
echo "Loading the NFS portmap daemon...";  portmap
