#!/bin/sh

export PATH=/System/Links/Executables:/System/Links/Tasks
export LD_LIBRARY_PATH=/System/Links/Libraries

echo "Loading udev task...";               Udev start
echo "Mounting file system read-write..."; mount -o remount,rw /
echo "Mounting remaining filesystems...";  mount -a
echo "Generating the issue file...";       GenIssue start
echo "Hiding the legacy tree...";          GoboHide start
echo "Loading kernel modules...";          LoadModules start
echo "Loading network settings...";        Network start
echo "Configuring hostname...";            Hostname start
echo "Loading syslogd and klogd...";       syslogd; klogd
# echo "Configuring swap space...";          Swap start
# echo "Loading mouse driver...";            Mouse start
# echo "Loading SSH daemon...";              /Programs/OpenSSH/Current/sbin/sshd
# echo "Loading the NFS portmap daemon...";  portmap
# echo "Loading the LIRC daemon...";         lircd
