#!/bin/sh

. GoboPath

# This file is called by Reboot and Halt
export PATH=$PATH:$goboTasks

echo "Stopping daemons";                      killall -9 klogd syslogd
echo "Stopping network interfaces";           Network stop
echo "Sending all processes the TERM signal"; killall5 -15; sleep 1
echo "Sending all processes the KILL signal"; killall5 -9
echo "Unmounting filesystems";                umount -a -r; swapoff -a
