#!/bin/sh

# Build a dummy Packages tree structures based on the host computer's /Programs directory.
# (Assumes a GoboLinux system.)

find /Programs -type d -mindepth 2 -maxdepth 2 | grep -v Settings | grep -v Variable | while read i
do
   name=`echo $i | cut -d/ -f3`
   vers=`echo $i | cut -d/ -f4`
   echo "$name"
   echo "$vers"
   mkdir -p Packages/$name/$vers
   cd /Programs/$name/$vers
   find . -printf "%y %P\n" > /tmp/manifest
   cd -
   mv /tmp/manifest Packages/$name/$vers/Manifest
done

