#!/bin/bash (source)

#
# packages known to be broken or that shouldn't be installed through Compile
#
blacklist=(
    # LibGCC and LibStdC++ are installed in a different way
    "LibGCC"
    "LibStdC++"
)

function is_in_blacklist() {
	ret=1
    for blacklist_entry in ${blacklist[@]}
    do
        [ "$1" = "$blacklist_entry" ] && { ret=0; break; }
	done
	return $ret
}
