#!/bin/bash (source)

function get_native_arch() {
    arch=`uname -m`
    case $arch in
        i686|i586|i486|i386) echo i686 ;;
        *) echo $arch
    esac
}

function get_chosen_arch() {
    [ "$CROSS_SH4" ]            && platform=SH4
    [ "$CROSS_ARM" ]            && platform=ARM
    [ "$CROSS_ARM_SOFT_FLOAT" ] && platform=ARM-SoftFP
    [ "$GLIBC_TOOLCHAIN" ]      && toolchain=Glibc
    [ "$UCLIBC_TOOLCHAIN" ]     && toolchain=uClibc
    [ "$DIETLIBC_TOOLCHAIN" ]   && toolchain=DietLibc
    [ "$NEWLIB_TOOLCHAIN" ]     && toolchain=Newlib
    echo $platform-$toolchain
}

function get_recipe_arch() {
    [ "$CROSS_ARM" = "y" -o "$CROSS_ARM_SOFT_FLOAT" = "y" ] && echo arm
    [ "$CROSS_SH4" = "y" ] && echo sh4
    [ "$CROSS_PPC" = "y" ] && echo ppc
    [ "$NATIVE_COMPILATION" = "y" ] && get_native_arch
}

function get_kernel_arch() {
    if [ "$NATIVE_COMPILATION" = "y" ]
    then
        arch=`uname -m`
        case $arch in
            i686|i586|i486|i386) echo i386 ;;
            *) echo $arch
        esac
    else
        echo "$cross_kernel_arch"
    fi
}
