#!/bin/sh (syntax highlighting marker)

function Get_Local_Trunk() {
   [ -d "$compileSubversionLocalTrunk/.svn" ] || return 1
   echo "$compileSubversionLocalTrunk"
}

function Get_Local_Revisions() {
   [ -d "$compileSubversionLocalRevisions/.svn" ] || return 1
   echo "$compileSubversionLocalRevisions"
}

function Subversion_Status() {
   svn status "$1" | sort -k1.8
}

function Subversion_Status_Match() {
   Subversion_Status "$2" | grep "^$1" | cut -b8-
}

function Subversion_Diff() {
   # {
   svn diff "$1" | Color_Output diff
   # svn diff does not show deleted contents. Let's emulate it:
   Subversion_Status_Match "D" "$1" | while read deleted
   do
      echo "Index: $deleted"
      echo "==================================================================="
      echo "--- $deleted   (deleted)"
      echo "@@ -0,0 +1,? @@"
      svn cat "$deleted" | awk '{ print "-" $0 }'
   done | Color_Output diff
   # } | less --quit-if-one-screen --RAW-CONTROL-CHARS
}

