#!/bin/sh

goboPrograms=/Programs

[ "$2" ] || {
   echo "Usage:   `basename $0` <package-file> <root>"
   echo "Example: `basename $0` Glibc--2.3.2--i686.tar.bz2 /Mount/Disk/"
   exit 1
} 

package=`readlink -f "$1"`
root="$2"

base=$(basename $package)
name=${base%%--*}
version=${base#*--}
version=${version%%--*}

echo "Installing $name version $version..."

pushd "$root/$goboPrograms" &> /dev/null
unpacked=$(dirname $package)/$name
if ! [ -d "$unpacked" ]
then
   pushd $(dirname $package) &> /dev/null
   tar xjpf "$package"
   popd &> /dev/null
fi

#cp -R "$unpacked" .
mkdir "$name"
mount --bind "$unpacked" "$name"
[ `ls "$name" | grep -v Settings | grep -v Variable | grep -v Current | wc -l` -gt 1 ] && {
   echo "MiniInstallPackage: too many versions inside directory $name. Bailing out."
   exit 1
}

dsettings="$name/$version/Resources/Defaults/Settings"
[ -d "$dsettings" ] && cp -R "$dsettings" "$name/Settings"
popd &> /dev/null

$(dirname $0)/MiniSymlinkProgram /Programs/$name/$version $root
