#!/bin/sh

#
# MiniSymlinkProgram
#  A minimal functionality SymlinkProgram
#
# based on RescueSymlinkProgram by
# (C) 2004 Andre Detsch. Released under the GNU GPL.
#     detsch at gobolinux.org
#
#
#############################################################################
# Changelog
#############################################################################
# 29/08/2004 - [detsch] - First version
#

scriptdir=$(readlink -f $(dirname $0))

if [ ! "$1" -o "$1" = "--help" ] 
then
   echo "MiniSymlinkProgram" 1>&2
   echo "A minimal functionality SymlinkProgram" 1>&2
   echo "Usage:   `basename $0` <program_path> <root>" 1>&2 
   echo "Example: `basename $0` /Programs/Glibc/Current /Mount/Disk" 1>&2 
   exit 1
fi

full_path="$1"
root=`readlink -f $2`
gobolinks=/System/Links

echo " MiniSymlinkProgram: Linking ${full_path} inside ${gobolinks}" 1>&2

#function do_link() {
#   if [ -d "$root/$1" ]
#   then
#      cd $root/$1
#      find -mindepth 1 -printf "%P\n" | while read file
#      do
#         dir=`dirname $root/$2/$file`
#         [ -L "$dir" ] && rm -f "$dir"
#         mkdir -p "$dir"
#         ln -nfs $1/$file $root/$2/$file
#      done
#      cd -
#   fi
#}

export verboseFD=100
export normalFD=101
export terseFD=102
export errorFD=103
export debugFD=104
export logFD=105
export questionFD=106
eval "exec $verboseFD>/dev/null"
eval "exec $normalFD>/dev/null"
eval "exec $terseFD<&2"
eval "exec $errorFD<&2"
eval "exec $debugFD>/dev/null"
eval "exec $logFD>/dev/null"

function do_link() {
   if [ -d "$root/$1" ]
   then
      cd $root/$2
      goboPrefix=$root goboPrograms=$root/Programs $scriptdir/LinkOrExpandAll $root/$1 --relative
      cd - &> /dev/null
   fi
}

do_link ${full_path}/bin ${gobolinks}/Executables
do_link ${full_path}/sbin ${gobolinks}/Executables
do_link ${full_path}/Resources/Wrappers ${gobolinks}/Executables
do_link ${full_path}/lib ${gobolinks}/Libraries
do_link ${full_path}/include ${gobolinks}/Headers
do_link ${full_path}/../Settings ${gobolinks}/../Settings
do_link ${full_path}/Shared ${gobolinks}/Shared

ln -nfs $(basename ${full_path}) $root/$(dirname ${full_path})/Current

echo " MiniSymlinkProgram: Done" 1>&2

exit 0
