#!/bin/bash

function download_packages() {
   mkdir -p Bootstrap
   rsync --verbose --progress --port=8730 -r -L rsync.gobolinux.org::$1/ Bootstrap/
}

function update_tools() {
    [ "$quiet" ] && echo "Fetching the ChrootCompile module from CVS..."
    cvs $cvsopts -d :pserver:anonymous@cvs.sv.gnu.org:/sources/goboscripts co tools/ChrootCompile 
    cvs $cvsopts -d :pserver:anonymous@cvs.sv.gnu.org:/sources/goboscripts co tools/Compile 
    cvs $cvsopts -d :pserver:anonymous@cvs.sv.gnu.org:/sources/goboscripts co tools/Scripts 
    ln -nfs tools/Scripts/bin/LinkOrExpandAll .
    ln -nfs tools/ChrootCompile/ChrootCompile .
    ln -nfs tools/ChrootCompile/MiniInstallPackage .
    ln -nfs tools/ChrootCompile/MiniSymlinkProgram .
    ln -nfs tools/ChrootCompile/GenericInstall .
}

function configure_tools() {
    {
       echo "chrootcompileCompileConf=$PWD/Compile.conf"
       echo "goboPrograms=/Programs"
    } > ChrootCompile.conf
    [ -e /System/Setting/gobo ] && echo "chrootcompileMode=gobo" >> ChrootCompile.conf
    cp tools/Compile/Resources/Defaults/Settings/Compile/Compile.conf .
}

unset quiet
if [ "$1" = "--quiet" ]
then
    quiet=yes
    wgetopts="--quiet"
    cvsopts="-Q"
fi

bootstraprepository="chrootcompile-packages"
if [ "$1" = "--complete" -o "$1" = "-c" ]
then
   bootstraprepository="livecd-packages"
fi


download_packages "$bootstraprepository"
update_tools
configure_tools

if [ -e "./SetupAddOn" ]
then
   chmod +x SetupAddOn
   ./SetupAddOn
fi

if [ ! "$quiet" ]
then
   echo
   echo
   echo "You can now add compilation recipes to the Recipes/ directory"
   echo "and run builds with ./ChrootCompile Recipes/App/Version"
   echo
   echo
fi
