#!/bin/sh

# File system check.
# Adapted from Linux From Scratch by Hisham Muhammad
# ps: never tested.
#

function ByeBye() {
   reset; clear
   echo -e "$1"; shift
   echo "Press Enter."; read
   "$@"
}

function HaltSystem() {
   ByeBye "$*\nThe system will be halted." halt -d -f -i -p
}

function RebootSystem() {
   ByeBye "$*\nThe system will be rebooted." reboot -d -f -i
}

if [ -e /fastboot ]
then
   exit 0
fi

mount -n -o remount,ro / || HaltSystem "Cannot check root file system."

if [ -e /forcefsck ]
then force="-f"
else force=""
fi

fsck $fsckOptions -p -C -T -A

case "$?" in
0|1) :
   ;;
2) RebootSystem \
   "File system errors were found and have been corrected, but\n" \
   "the nature of the errors require this system to be rebooted."
   ;;
*) HaltSystem \
   "File system errors were encountered that couldn't be\n" \
   "fixed automatically. This system cannot continue to boot\n" \
   "and will therefore be halted until those errors fixed manually\n" \
   "by a System Administrator."
   ;;
esac # is ridiculous.
