#!/bin/sh

#
# Bring up or down one specific network interface.
# This function is called by the Network task, for each interface
# listed in the NetworkInterfacesOnBoot array.
# It can also be called directly in the command line for any
# specific interface
#
# Example: StartTask NetworkInterface eth0
# Hacked by Guilherme Bedin, Hisham Muhammad and many others - 26/07/2003
#

source GoboPath
source ${goboSettings}/BootOptions
source ${goboSettings}/NetworkOptions 2> /dev/null


#
# Evaluate variables configured at NetworkOptions
#
bootproto=`eval 'echo $'$2'_BootProto'`
ip=`eval 'echo $'$2'_IP'`
netmask=`eval 'echo $'$2'_Netmask'`
broadcast=`eval 'echo $'$2'_Broadcast'`


#
# Brings a statically assigned interface up or down
#
function StaticNetworkInterface() {
   interface="$2"
   case "$1" in
      [Ss]tart)
         [ -z "$netmask" ]   && netmask=255.255.255.0
         [ -z "$broadcast" ] && broadcastcmd="" || broadcastcmd="broadcast $broadcast"
         ifconfig $interface $ip netmask $netmask $broadcastcmd
         if [ -n "$Gateway" -a "$GatewayInterface" = "$interface" ]
         then route add default gateway $Gateway metric 1 dev $GatewayInterface
         fi
         ;;
      [Ss]top)
         # the default gateway is removed when the interface on which it's binded goes down
         ifconfig $interface down
         ;;
   esac
}


if [ "$bootproto" = "DHCP" ]
then DHCPNetworkInterface "$1" "$2" $DHCPTimeout
else StaticNetworkInterface "$1" "$2"
fi
