#!/bin/sh

source GoboPath
source ${goboSettings}/BootOptions
source ${goboSettings}/NetworkOptions 2> /dev/null

#
# Bring up or down all network interfaces listed 
# in the NetworkInterfacesOnBoot array.
# This is normally called on system boot and shutdown.
# Hacked by Guilherme Bedin, Hisham Muhammad and many others - 26/07/2003
#

for interface in "${NetworkInterfacesOnBoot[@]}"
do
   NetworkInterface "$1" "${interface}"
done


