#!/bin/sh

source GoboPath
source ${goboSettings}/BootOptions
if [ -r "${goboSettings}/NetworkOptions" ]; then
   source ${goboSettings}/NetworkOptions 2> /dev/null
fi

#
# Bring up or down either a specific network interface,
# or all network interfaces listed in the NetworkInterfacesOnBoot array.
# This is normally called on system boot and shutdown.
# It can also be called directly in the command line for any
# specific interface.
# Hacked by Guilherme Bedin, Hisham Muhammad and many others - 26/07/2003
#

#
# Brings a statically assigned interface up or down
#
function StaticNetworkInterface() {
   unset broadcastcmd
   interface="$2"
   case "$1" in
      [Ss]tart)
         [ -z "$networkNetmask" ]   && networkNetmask=255.255.255.0
         [ -n "$networkBroadcast" ] && broadcastcmd="broadcast $networkBroadcast"
         ifconfig $interface $networkIP netmask $networkNetmask $broadcastcmd
         if [ -n "$Gateway" -a "$GatewayInterface" = "$interface" ]
         then route add default gateway $Gateway metric 1 dev $GatewayInterface
         fi
         ;;
      [Ss]top)
         # the default gateway is removed when the interface which it is bound to goes down
         ifconfig $interface down
         ;;
   esac
}

function NetworkInterface() {
   eval 'export networkBootProto=$'$2'_BootProto'
   eval 'export networkIP=$'$2'_IP'
   eval 'export networkNetmask=$'$2'_Netmask'
   eval 'export networkBroadcast=$'$2'_Broadcast'
   if [ -z "$networkBootProto" -o "$networkBootProto" = "Static" ]
   then StaticNetworkInterface "$1" "$2"
   else source ${networkBootProto}NetworkInterface "$1" "$2"
   fi
}

if [ "$2" ]
then
   NetworkInterface "$@"
else
   for interface in "${NetworkInterfacesOnBoot[@]}"
   do
      NetworkInterface "$1" "$interface"
   done
fi
