#!/bin/sh

source /System/Settings/BootOptions


# Bring up or down all network interfaces listed 
# in the NetworkInterfacesOnBoot array.
# This is normally called on system boot and shutdown.
# Hacked by Guilherme Bedin, Hisham Muhammad and many others - 26/07/2003
#

for interface in "${NetworkInterfacesOnBoot[@]}"
do
   NetworkInterface "$1" "${interface}"
done


