#!/bin/sh

#
# Bring up or down one specific network interface.
# This function is called by the Network task, for each interface
# listed in the NetworkInterfacesOnBoot array.
# It can also be called directly in the command line for any
# specific interface
# Example: StartTask NetworkInterface eth0
# Hacked by Guilherme Bedin, Hisham Muhammad and many others - 26/07/2003
#

source /System/Settings/BootOptions

bootproto=`eval 'echo $'$2'_BootProto'`
ip=`eval 'echo $'$2'_IP'`
netmask=`eval 'echo $'$2'_Netmask'`
broadcast=`eval 'echo $'$2'_Broadcast'`

[  -z  "${bootproto}" ] && bootproto=Static
"${bootproto}NetworkInterface" "$1" "$2"
