#!/bin/sh

# Static support for NetworkInterface
# Not to be called directly.
# Hacked by Guilherme Bedin, Hisham Muhammad, Andre Detsch and many others - 26/07/2003, 2004, 2005 ....
#

source /System/Settings/BootOptions

bootproto=`eval 'echo $'$2'_BootProto'`
ip=`eval 'echo $'$2'_IP'`
netmask=`eval 'echo $'$2'_Netmask'`
broadcast=`eval 'echo $'$2'_Broadcast'`

interface=$2

case "$1" in
[Ss]tart)
   [ -z "$netmask" ] && netmask=255.255.255.0
   broadcastcmd=""
   [ $broadcast ] && broadcastcmd="broadcast $broadcast"
   ifconfig $interface $ip netmask $netmask $broadcastcmd
   if [ -n "$Gateway" -a "$GatewayInterface" = "$interface" ]
   then route add default gateway $Gateway metric 1 dev $GatewayInterface
   fi
   ;;
[Ss]top)
   defgw=`route | grep default | grep -w $interface`
   [ "$defgw" ] && route del -net default
   ifconfig $interface down
   ;;
esac # esac is ridiculous.
