#!/bin/sh

. $BootScriptsDir/Functions/ConsoleToolkit

DisplayBanner() {
   Color $White $Black
   clear
   echo -en '\007'
   PrintAt $[COLUMNS/2-5] 1 "GOBOLINUX"
   for ((i=1; i<=ROWS-2; i++))
   do echo
   done
}

ThemeFile() {
   file=`echo $1 | tr [:lower:] [:upper:]`
   echo "]LOAD \"$file\""
}

ThemeBefore() {
   local id=$1
   shift
   msg=`echo $* | tr [:lower:] [:upper:]`
   case $[RANDOM%5] in
   0) echo "]$[id*10] PRINT \"$msg\"" ;;
   1) echo "]$[id*10] REM *** $msg ***" ;;
   2) echo "]$[id*10] GOSUB $[RANDOM]0 : PRINT \"$msg\"" ;;
   3) echo "]$[id*10] IF A\$=\"Q\" THEN M\$=\"$msg\"" ;;
   4) echo "]$[id*10] PRINT CHR\$(4);\"$msg\"" ;;
   esac # is ridiculous
}

ThemeAfter() {
   local id=$1
   local ret=$2
   if [ $ret -gt 0 ]
   then echo -e "\007?SYNTAX ERROR IN $[id*10]\n\n]"
   fi
}

ThemeFinish() {
   if [ -p "$fifo" ]
   then
      echo done > $fifo
      kill $fifopid &> /dev/null
      echo "]HOME"
      clear
      echo "]HOME"
      usleep 250000
      clear
   fi
   {
   echo "]CATALOG"
   echo
   echo " DISK VOLUME 254"
   echo
   ls -p / | grep "/$" | tr -d "/" | while read line
   do
      size=$(printf "%.3d" $(ls /"$line" | wc -l))
      echo -e " B $size $line" | tr [:lower:] [:upper:]
   done
   echo " A 002 LOGIN"
   echo 
   echo "]LOAD \"LOGIN\""
   echo "]RUN"
   echo
   echo "WELCOME TO GOBOLINUX."
   echo
   } > "$1"
}

ThemeInit() {
   fifo="${goboTemp}/BootScript.AppleII.theme.hack"
   mkfifo "$fifo" &> /dev/null
   if [ -p "$fifo" ]
   then
      ThemeStdoutStream=$fifo
      ThemeStderrStream=$fifo
      {
         cmd=
         while [ ! "$cmd" = "done" ]
         do
            read < $fifo
            rep=`echo $REPLY | tr [:lower:] [:upper:]`
            echo $rep
         done
      } &
      fifopid=$!
   else
      ThemeStdoutStream=/dev/null
      ThemeStderrStream=/dev/null
   fi
   clear
   Color $Black $White
   FillBox 1 1 $[COLUMNS] $[ROWS] "@" 
   usleep 250000
   DisplayBanner
   usleep 250000
   GotoXY 1 $ROWS
   echo "]NEW"
   echo "]5 TEXT: NORMAL: HOME"
}

