#!/bin/sh

source "$BootScriptsDir/Functions/ConsoleToolkit"

### Theme Internal Functions ###

scrollStart=7
screenY=$scrollStart

DisplayBanner() {

   count_cpus() {
      cat /proc/cpuinfo | grep -i "model name" | wc -l
   }

   parse_cpu() {
      line=`cat /proc/cpuinfo | grep -i "$1" | head -n 1`
      echo ${line##*:[ ]}
   }

   parse_mem() {
      mem=`cat /proc/meminfo | grep -i "MemTotal"`
      echo ${mem##*:}
   }

   echo -n "GoboLinux "`cat /System/Settings/GoboLinuxVersion`" "
   uname -m
   echo -n "Linux kernel version "
   uname -r
   uname -v
   [ `count_cpus` -gt 1 ] && plural=s || plural=
   echo `count_cpus` `parse_cpu "model name" 1` processor$plural \(`parse_cpu "cpu MHz" 1` MHz\)
   echo `parse_mem` total memory
   echo
}

CoolWrite() {
   x=1
   y=1
   while read -n 1 -d"\0"
   do
      if [ "$REPLY" = "
" ]
      then
         Cursor Save
         PrintAt $x $y " "
         Cursor Restore
         y=$[y+1]
         x=1
      else
         Cursor Save
         PrintAt $x $y "$REPLYa" $FGBoldGreen
         Cursor Restore
         x=$[x+1]
      fi
      usleep 25000
   done
}

### Theme API ###

ThemeInit() {
   ThemeStdoutStream=/dev/null
   ThemeStderrStream=/dev/null
   Cursor Off
   clear
   DisplayBanner | CoolWrite &
}

ThemeFile() {
   :
}

ThemeBefore() {
   local id=$1
   shift
   pos[$id]=$screenY
   PrintAt 4 $screenY "$*" $FGBlue
   msg[$id]="$*"
   ClearEOL
   screenY=$[screenY+1]
   [ "$screenY" -ge "$[ROWS-2]" ] && screenY=$scrollStart
   HideOutputHack
   return 0
}

ThemeAfter() {
   ScrollArea 1 $[ROWS]
   local y=${pos[$1]}
   if [ "$2" = "0" ]
   then PrintAt 2 $y "*" $FGBoldGreen
   else PrintAt 2 $y "!" $FGYellow $BGRed
   fi
   PrintAt 4 $y "${msg[$1]}" $FGBoldBlue $BGBlack
   HideOutputHack
}

ThemeFinish()
{
   clear > "$1"
   Color $Green $Black Bold >> "$1"
   DisplayBanner >> "$1"
   Color $Default >> "$1"
   Cursor On
}
