#!/bin/sh

# Progress (formerly known as GoboText-II)
#
# ...and you thought GoboText was overkill. ;-)

source $BootScriptsDir/Functions/ConsoleToolkit

mode="$1"
runlevel="$2"

[ -e "/System/Kernel/Devices/fb/0" ] && framebuffer="yes"

gradient=(4 3 1 5 7 9 10 2 6 8 11)

banner=(
"]R]P0000000]P16f75c0]P26fc0b4]P37c6fc0]P48e6fc0]P56f87c0]P66fc0a2]P76f98c0]P86fc090]P96faac0]Pa6fbcc0]Pb6fc07f]Pc000000[K(U[0m[30m[45mﬂ[31m[44mﬂ[34m[40mﬂ[33m[40mﬂ[33m[40mﬂ[31m[40mﬂ[33m[40mﬂ[30m€[30m€[30m€[30m€[30m€[30m€[30m€[30m€[30m€[33m[45mﬂ[34m[41mﬂ[30m€[30m€[30m€[30m€[30m€[30m€[30m€[30m€[30m€[30m€[30m€[30m€[30m€[30m€[33m[41mﬂ[33m[41mﬂ[30m€[30m€[30m€[30m€[30m€[31m€[33m[41mﬂ[30m€[30m€[30m€[30m€[30m€[30m€[30m€[30m€[30m€[30m€[30m€[30m€[30m€[30m€[30m€[30m€[30m€[30m€[30m€[30m€[30m€[30m€[30m€[30m€[0m"
"[33m[47mﬂ[37m[41mﬂ[30m€[30m€[30m€[30m€[30m€[30m€[30m€[1;31m[40m‹[0m[30m[47mﬂ[1;31m[40m‹[0m[30m[41mﬂ[30m[45mﬂ[30m€[30m€[35m[43mﬂ[33m[47mﬂ[1;31m[40m‹[0m[30m[45mﬂ[30m[47mﬂ[1;31m[40m‹[0m[30m€[0m[30m€[0m[30m€[0m[30m[47mﬂ[30m[47mﬂ[1;31m[40m‹[0m[30m[45mﬂ[30m[47mﬂ[30m€[30m€[1;31m[45mﬂ[0m[1;31m[45m‹[0m[30m€[0m[30m€[0m[30m€[0m[30m€[0m[30m€[0m[30m[47mﬂ[30m[47mﬂ[30m€[30m[47mﬂ[1;31m[40m‹[0m[30m[47mﬂ[30m[47mﬂ[30m[47mﬂ[30m[43mﬂ[30m€[30m€[30m[47mﬂ[30m[47mﬂ[30m€[30m€[30m€[30m[47mﬂ[30m[47mﬂ[30m€[30m[47mﬂ[30m[47mﬂ[30m€[30m€[30m€[30m[41mﬂ[30m[45mﬂ[0m"
"[1;31m€[0m[1;32m[42m‹[0m[30m€[0m[35m[40mﬂ[35m[40mﬂ[37m[42mﬂ[35m[42mﬂ[30m€[32m[46mﬂ[1;31m[45m‹[0m[30m€[0m[30m€[0m[30m€[0m[1;32m[45m‹[0m[37m€[0m[30m€[0m[1;31m[42mﬂ[0m[1;31m[47mﬂ[0m[30m€[0m[30m€[0m[30m€[0m[1;31m€[0m[1;31m[45m‹[0m[30m€[0m[1;31m€[0m[1;31m[47m‹[0m[30m€[0m[30m€[0m[30m€[0m[1;31m€[0m[1;31m[42mﬂ[0m[30m€[0m[1;31m[45m‹[0m[1;32m[47m‹[0m[30m€[0m[30m€[0m[30m€[0m[30m€[0m[30m€[0m[1;32m[42mﬂ[0m[1;32m[45m‹[0m[30m€[0m[1;32m€[0m[1;31m[47m‹[0m[30m€[0m[30m€[0m[30m€[0m[1;31m[47m‹[0m[1;32m[47mﬂ[0m[30m€[0m[1;32m[47mﬂ[0m[1;31m[47m‹[0m[30m€[0m[30m€[0m[30m€[0m[1;31m[47mﬂ[0m[37m€[0m[30m€[0m[30m€[0m[37m[40mﬂ[1;31m€[0m[1;32m[40m‹[0m[1;31m[45m‹[0m[1;31m[40mﬂ[0m[30m€[0m"
"[0m[32m€[0m[1;32m[46mﬂ[0m[30m€[0m[30m€[0m[30m€[0m[32m[46mﬂ[1;32m€[0m[30m€[0m[36m[42mﬂ[32m€[30m€[30m€[30m€[1;32m[42mﬂ[0m[37m[46mﬂ[30m€[1;30m[42m‹[0m[1;31m[46mﬂ[0m[30m€[0m[30m€[0m[30m€[0m[1;31m[46mﬂ[0m[1;30m[46m‹[0m[30m€[0m[1;31m[46mﬂ[0m[1;30m[42m‹[0m[30m€[0m[30m€[0m[30m€[0m[32m[46mﬂ[1;32m[46mﬂ[0m[30m€[0m[36m€[0m[1;33m[42m‹[0m[30m€[0m[30m€[0m[30m€[0m[30m€[0m[30m€[0m[1;31m[42mﬂ[0m[1;32m[46mﬂ[0m[30m€[0m[1;30m€[0m[1;33m[42m‹[0m[30m€[0m[30m€[0m[30m€[0m[1;30m[46m‹[0m[1;30m[47m‹[0m[30m€[0m[1;30m[42m‹[0m[1;31m[42mﬂ[0m[30m€[0m[30m€[0m[30m€[0m[1;33m[42m‹[0m[32m[46mﬂ[30m€[30m€[30m€[1;31m[46mﬂ[0m[1;32m[46mﬂ[0m[36m[42mﬂ[30m€[30m€[0m"
"[1;30m[40mﬂ[0m[1;30m[42mﬂ[0m[1;30m[40m‹[0m[30m[42mﬂ[1;33m[40m‹[0m[1;30m[46m‹[0m[1;30m[46mﬂ[0m[30m€[0m[1;30m[40mﬂ[0m[1;33m[46m‹[0m[1;30m[40m‹[0m[1;33m[40m‹[0m[30m[46mﬂ[1;33m[46mﬂ[0m[32m[40mﬂ[30m€[32m[46mﬂ[1;33m[46m‹[0m[30m[42mﬂ[1;30m[40m‹[0m[1;33m[40m‹[0m[36m€[0m[32m[40mﬂ[30m€[1;30m[40mﬂ[0m[1;30m[42m‹[0m[1;33m[40m‹[0m[1;33m[40m‹[0m[1;30m[40m‹[0m[1;33m€[0m[36m[40mﬂ[30m€[1;30m€[0m[1;30m[46mﬂ[0m[1;33m[40m‹[0m[1;33m[40m‹[0m[1;33m[40m‹[0m[1;33m[40m‹[0m[30m€[0m[1;30m[46mﬂ[0m[1;30m[46mﬂ[0m[30m€[0m[1;33m[42m‹[0m[1;30m[46mﬂ[0m[30m€[0m[30m€[0m[30m€[0m[1;30m[46mﬂ[0m[1;33m[42m‹[0m[30m€[0m[1;30m[40mﬂ[0m[1;30m[46m‹[0m[1;33m[40m‹[0m[1;33m[40m‹[0m[30m[46mﬂ[1;33m€[0m[1;33m[42m‹[0m[30m€[0m[1;30m[40m‹[0m[1;32m[46mﬂ[0m[1;30m[40mﬂ[0m[30m€[0m[36m[40mﬂ[1;30m[46mﬂ[0m[1;33m[40m‹[0m"
"(B"
)

##########
#
# UI elements
#
##########

function DrawTopLogo() {
GotoXY 1 $[ROWS/2-2]
spaces=""
for (( i = 0 ; i < COLUMNS/2-34; i++ ))
do spaces=" $spaces"
done

for line in "${banner[@]}"
do
   echo "[0m${spaces}${line}"
done

}

#########

function countExecs() {
   local mode
   # a cheat that works on the common case
   [ "$PREVLEVEL" = "N" ] && mode=/System/Settings/BootScripts/BootUp || mode=/System/Settings/BootScripts/Shutdown
   cat "$1" $mode | sed 's/#.*$//g' | grep Exec | wc -l | awk '{ print $1 }'
}

function PrintStatus()
{
    Cursor Save
    RepeatAt 1 $ROWS $[COLUMNS-1] " "
    case "$1" in
    Success)
        ;;
    Warning)
        shift
        PrintAt 3 $ROWS "Passed: $*" $FGYellow
        $ColorWhite
        ;;
    Failure)
        shift
        PrintAt 3 $ROWS "Failed: $*" $FGRed
        $ColorWhite
        ;;
    esac
    Cursor Restore
}

function Is_Bold() {
   [[ "$1" -ge 8 ]]
}

function Set_FG_Color() {
   if ! Is_Bold "$1"
   then
      echo -n "\033[0;"$[30+$1]"m"
   else
      echo -n "\033[1;"$[22+$1]"m"
   fi
}

function Hex() {
   letters=("a" "b" "c" "d" "e" "f")
   lo=$[$1 % 16]
   hi=$[($1 - lo) / 16]
   if [ "$hi" -ge 10 ]
   then echo -n ${letters[$[hi-10]]}
   else echo -n $hi
   fi
   if [ "$lo" -ge 10 ]
   then echo -n ${letters[$[lo-10]]}
   else echo -n $lo
   fi
}

bar=""
lastI=0
n=0
function UpdateProgress() {
   [[ $ProgressPercent -gt 99 ]] && ProgressPercent=99
   width=$[COLUMNS*(ProgressPercent)/100]
   steps=${#gradient[@]}
   step=$[COLUMNS/steps]
   for (( i = lastI ; i < width ; i++ ))
   do
      if [ "$framebuffer" ]
      then
         level=$[i*255/COLUMNS]
         invlevel=$[(COLUMNS-i)*255/COLUMNS]
         color=00`Hex $level``Hex $invlevel`
         bar="$bar\033]Pc${color}\033[1;34m€"
      else
         if [ $[i%step] -eq 0 -a "$n" -lt "$steps" ]
         then
            bar="$bar"`Set_FG_Color "${gradient[n]}"`
            n=$[n+1]
         fi
         bar="${bar}€"
      fi
   done
   lastI=$[width]
   Cursor Save
   GotoXY 1 $[ROWS-1]
   echo -en "\033[0m\033(U${bar}\033[0m\033D"
   Cursor Restore
}

scroll=$[ROWS/5]
STATUS_START=$[ROWS-(scroll+2)]
let STATUS_SIZE=$[scroll]

ColorWhite="echo -en \\033[1;35m"
ColorYellow="echo -en \\033[1;36m"
ColorRed="echo -en \\033[1;37m"


##### API #####

ThemeStdoutStream=/dev/null
ThemeStderrStream=/dev/null
#ThemeStdoutStream=/dev/console
#ThemeStderrStream=/dev/console

ThemeFile() {
   ProgressPercent=0
   ModeExecs=`countExecs "$goboSettings/BootScripts/$1"`
   (( ModeExecs < 1 )) && ModeExecs=100
   ProgressStep=$[(100-ProgressPercent)/ModeExecs]
}

ThemeBefore() {
   ProgressPercent=$[ProgressPercent+ProgressStep]
   UpdateProgress "$ProgressPercent"
   GotoXY 1 $[STATUS_START+STATUS_SIZE]
   id=$1
   shift
   echo "$*"
   msg[$id]="$*"
}

ThemeAfter() {
   [[ $2 -gt 0 ]] && PrintStatus Failure "${msg[$1]}"
   return $ExecReturn
}


ThemeInit() {
   clear
   # cheat:
   setfont "$ConsoleFont"

   DrawTopLogo

   GotoXY 1 $[STATUS_START+STATUS_SIZE]
   $ColorWhite
   Cursor off
   Cursor Save
   SetPalette "d" "808080"
   SetPalette "e" "ffff00"
   SetPalette "f" "ff0000"
   ScrollArea $STATUS_START $[STATUS_START+STATUS_SIZE]
}

function ThemeFinish() {
   (
      clear
      echo
      echo "[36;1mWelcome to GoboLinux `cat ${goboSettings}/GoboLinuxVersion`."
      echo
      SystemInfo
      echo "[36;22mTerminal......: [34;1m\l"
      echo "[33;1m"
   ) > $1
   $ColorWhite
   ScrollArea 0 ${ROWS}
   Cursor on
   clear
   ResetPalette
}
