#!/bin/sh

#
# "Quotes" GoboLinux Boot Script Theme
#
# Indicates success or failure as the boot progresses by displaying
# random short quotes
#
# Leandro Motta Barros
#


#
# Parameters
#

Mode="$1"



#
# Colors
#

ColorDefault="\\033[0;39m"   # Light gray
ColorHighlight="\\033[1;37m" # White
ColorLowdark="\\033[1;30m"   # Darkgray (BTW, lowdark is the opposite of highlight :-)
ColorSuccess="\\033[1;32m"   # Light green
ColorFailure="\\033[1;31m"   # Red
ColorSession="\\033[1;34m"   # Dark blue



#
# The quotes
#

SuccessQuotes=(
"It works! I can't believe it!"
#   -- Dr. Fred Edison (Day of the Tentacle)

"Okeydokey!"
#   -- Guybrush Threepwood (Secret of Monkey Island)

"Yes, my Lord!"
#   -- ??? (someone in Warcraft?)

"Yesssssss!"
#   -- Lode (XLode)

"Yooooo-hoooo!"
#   -- ???
)


FailureQuotes=(
"Argh!"
#   -- ???

"Houston, we have a problem!"
#   -- Jim Lovell

"That's not good... not good!"
#   -- Groove "Swinger" (Interstate 76)

"Damn!"
#   -- Duke Nukem (et al :-) 

"Ooooops..."
#   -- ???

"Oh dear... oh my..."
#   -- Hardy Har Har
#      (thanks to Ronn Webb (www.wingnuttoons.com) for the original quote
#      in English)
)



#
# The functions to print random quotes
#
function PrintSuccessMessage()
{
   echo -e "${ColorSuccess}${SuccessQuotes[RANDOM%${#SuccessQuotes[*]}]}${ColorDefault}"
}

function PrintFailureMessage()
{
   echo -e "${ColorFailure}${FailureQuotes[RANDOM%${#FailureQuotes[*]}]}${ColorDefault}"
}


#
# Functions necessary to make the theme work
#

function ThemeInit() {
   ThemeStdoutStream=/dev/console
   ThemeStderrStream=/dev/console
}

function ThemeFile() {

   #
   # Hello/Goodbye message
   #

   if [ "$PREVLEVEL" = "N" ]
   then
      echo
      echo
      echo -e "${ColorLowdark}  -------------------------------------------------"
      echo -e -n "${ColorDefault}   Wait a little bit, "
      echo -e -n "${ColorHighlight}GoboLinux"
      echo -e "${ColorDefault} is initializing..."
      echo -e "${ColorLowdark}  -------------------------------------------------${ColorDefault}"
   else
      echo
      echo
      echo -e "${ColorLowdark}  --------------------------------------------------------"
      echo -e -n "${ColorDefault}   Wait another little bit, "
      echo -e -n "${ColorHighlight}GoboLinux"
      echo -e "${ColorDefault} is going down..."
      echo -e "${ColorLowdark}  --------------------------------------------------------${ColorDefault}"
   fi
}

function ThemeBefore()
{
   shift
   echo -e "$* ${ColorLowdark}"
}

function ThemeAfter()
{
   ExecReturn=$2
   [ $ExecReturn = 0 ] && PrintSuccessMessage ||  PrintFailureMessage
   echo -e "${ColorSession} _.-._.-._.-._.-._.-._.-._.-._.-._.-._.-._.-._.-._ ${ColorDefault}"
   return $ExecReturn
}

function ThemeFinish()
{
   echo
   echo -e -n "${ColorDefault}  Ok, ${ColorHighlight}GoboLinux${ColorDefault} is up and running."
   echo
   echo
   {
      SystemInfo
      echo
   } > "$1"
}
