#!/bin/sh

source $BootScriptsDir/Functions/ConsoleToolkit

ThemeStdoutStream=/dev/null
ThemeStderrStream=/dev/null

### Theme Internal Functions ###

scrollStart=5
screenY=$scrollStart
maxScroll=$[ROWS-5]

DisplayBanner() {

   count_cpus() {
      cat /proc/cpuinfo | grep -i "model name" | wc -l
   }

   parse_cpu() {
      line=`cat /proc/cpuinfo | grep -i "$1" | head -n 1`
      echo ${line##*:[ ]}
   }

   parse_mem() {
      mem=`cat /proc/meminfo | grep -i "MemTotal"`
      echo ${mem##*:}
   }

   echo -n "GoboLinux "`cat /System/Settings/GoboLinuxVersion`" "
   uname -m
   echo -n "Linux kernel version "
   uname -r
   uname -v
   [ `count_cpus` -gt 1 ] && plural=s || plural=
   echo `count_cpus` `parse_cpu "model name" 1` processor$plural \(`parse_cpu "cpu MHz" 1` MHz\)
   echo `parse_mem` total memory
   echo
}

### Theme API ###

ThemeInit() {
   Cursor Off
   Color $White $Blue
   clear
   Color $Cyan $Blue Bold
   echo -n "GoboLinux "
   cat /System/Settings/GoboLinuxVersion
   FillLineWith "-"
   GotoXY 1 $[ROWS-2]
   FillLineWith "-"
   Color $Black $White
   Window 3 4 $[COLUMNS-3] $[ROWS-4]
}

ThemeFile() {
   :
}

ThemeBefore() {
   local id=$1
   shift
   pos[$id]=$screenY
   RepeatAt 4 $screenY $[COLUMNS-8] " " $FGGray $BGWhite
   PrintAt 9 $screenY "$*" $FGGray $BGWhite
   msg[$id]="$*"
   screenY=$[screenY+1]
   [ "$screenY" -ge "$maxScroll" ] && screenY=$scrollStart
   HideOutputHack $Blue
   return 0
}

ThemeAfter() {
   local y=${pos[$1]}
   if [ "$2" = "0" ]
   then PrintAt 5 $y "[*]" $FGBlue $BGWhite
   else PrintAt 5 $y " ! " $FGYellow $BGRed
   fi
   PrintAt 9 $y "${msg[$1]}" $FGBlack $BGWhite
   HideOutputHack $Blue
}

ThemeFinish()
{
   Color $White $Black
   clear > "$1"
   Color $Cyan $Black Bold >> "$1"
   DisplayBanner >> "$1"
   Cursor On
}
