#!/bin/sh

ThemeInit() {
   ThemeStdoutStream=/dev/console
   ThemeStderrStream=/dev/console
}

ThemeFile() {
   :
}

ThemeBefore() {
   shift
   echo "$@"
}

ThemeAfter() {
   shift
   if [ "$1" -gt 0 ]
   then
      echo "(Exited with error code $1)"
   fi
}

ThemeFinish()
{
    echo > "$1"
}
