#!/bin/sh

source /Programs/BootScripts/Current/Functions/ConsoleToolkit

### UI elements ###

function DrawTopLogo() {
GotoXY 1 1
spaces=""
for (( i = 0 ; i < COLUMNS/2-34; i++ ))
do spaces=" $spaces"
done

$ColorTop
echo -e "[K(U
[K${spaces}ÜÛßßßßß         ÛÛ              ÛÛ       ÛÛ
[K${spaces}ÛÛ       ÜÜÜÜÜ  ÛÛÜÜÜÜ   ÜÜÜÜÜ  ÛÛ       ÜÜ  ÜÜÜÜÜÜ  ÜÜ   ÜÜ ÜÜ   ÜÜ
[K${spaces}ÛÛ ßßÛÛ ÛÛ   ÛÛ ÛÛ   ÛÛ ÛÛ   ÛÛ ÛÛ       ÛÛ  ÛÛ   ÛÛ ÛÛ   ÛÛ  ßÛÜÛß
[K${spaces}ÛÛ   ÛÛ ÛÛ   ÛÛ ÛÛ   ÛÛ ÛÛ   ÛÛ ÛÛ       ÛÛ  ÛÛ   ÛÛ ÛÛ   ÛÛ   ÛÛÛ
[K${spaces}ßÛÜÜÜÛÛ ßÛÜÜÜÛß ÛÛÜÜÜÛß ßÛÜÜÜÛß ÛÛÜÜÜÜÜ  ÛÛ  ÛÛ   ÛÛ ßÛÜÜÜÛÛ ÜÛß ßÛÜ(B"
$ColorBar
FillLineWith "Ü"
}

function DrawBottom() {
GotoXY 1 $[ROWS-1]
$ColorBar
FillLineWith "ß"
$ColorBottom
echo -en "\n[K"
}

function DrawStatusArea() {
$ColorStatus
GotoXY 1 $STATUS_START
for (( i=0 ; i < STATUS_SIZE ; i++ ))
do echo -e "[K"
done
$ColorBar
FillLineWith "Ü"
}

function WriteAtMain() {
   ScrollArea $[STATUS_START+STATUS_SIZE+1] $[ROWS-2]
   Cursor Restore
   # Don't know why I need this to make it work
   echo -n
}

function WriteAtBottom() {
   GotoXY 1 $[ROWS]
   $ColorBottom
}

function WriteAtStatus() {
   ScrollArea $[STATUS_START] $[STATUS_START+STATUS_SIZE-1]
   GotoXY 1 $[STATUS_START+STATUS_SIZE-1]
   $ColorStatus
   ClearLine
}

##########
#
# Customization
#
##########

STATUS_START=8
STATUS_SIZE=$(( (ROWS-STATUS_START-2)/2 ))

ColorTop="echo -en \\033[0;36m"
ColorStatus="echo -en \\033[0;44;37m"
ColorBottom="echo -en \\033[0;44;36m"
ColorBar="echo -en \\033[38m"

ColorWhite="echo -en \\033[0;40;39m"
ColorGreen="echo -en \\033[1;42;37m"
ColorYellow="echo -en \\033[0;43;30m"
ColorRed="echo -en \\033[1;41;37m"

SetPalette 3 "ffff00"

PrintStatus()
{
    case "$1" in
    Success)
        $ColorGreen
        echo -n "   OK   "
        ;;
    Warning)
        $ColorYellow
        echo -n " PASSED "
        ;;
    Failure)
        $ColorRed
        echo -n " FAILED "
        ;;
    esac
}

### API ####

ThemeStdoutStream=/dev/console
ThemeStderrStream=/dev/console

ThemeInit() {
   clear
   # cheat: setfont "$ConsoleFont"
   DrawTopLogo
   DrawStatusArea
   DrawBottom
   GotoXY 1 $[STATUS_START+STATUS_SIZE+1]
   $ColorWhite
   Cursor off
   Cursor Save
}

PrintStatus()
{
    case "$1" in
    Success)
        $ColorGreen
        echo -n "   OK   "
        ;;
    Warning)
        $ColorYellow
        echo -n " PASSED "
        ;;
    Failure)
        $ColorRed
        echo -n " FAILED "
        ;;
    esac
}

ThemeFile() {
   CurrFile=$1
}

ThemeBefore() {
   local id=$1
   shift
   WriteAtStatus
   echo -n "         $*"
   WriteAtBottom
   ClearLine
   echo -n "$CurrFile: $*"
   msg[$id]="$*"
   WriteAtMain
}

ThemeAfter() {
   local id=$1
   Cursor Save
   WriteAtStatus
   [ $2 = 0 ] && PrintStatus Success || PrintStatus Failure
   $ColorStatus
   echo " ${msg[$id]}"
   WriteAtMain
   return $ExecReturn
}

ThemeFinish() {
   (
      clear
      echo
      echo "[36;1mWelcome to GoboLinux `cat ${goboSettings}/GoboLinuxVersion`."
      echo
      SystemInfo
      echo "[36;22mTerminal......: [34;1m\l"
      echo "[33;1m"
   ) > "$1"
   $ColorWhite
   ScrollArea 0 ${ROWS}
   clear
   Cursor on
   ResetPalette
}
