#!/bin/sh

### Changelog #################################################################

# 2005/10/08 - [calica] First version

### Imports ###################################################################

source ScriptFunctions
Import GoboLinux
Import OptionParser
Import String
Import CVSTranslate

### Options ###################################################################

scriptDescription="Test the CVS translate functions"
scriptCredits="Copyright (C) 2005 Released under the GNU GPL."
#helpOnNoArguments=yes
scriptUsage="<options> <recipe_tarballs>"
#scriptExample="-b -e entry_value File1"
#scriptNotes="<recipe> can be directory or tarball"
#Add_Option_Boolean "b" "bool" "A boolean option."
#Add_Option_Entry "e" "entry" "Specify <entry>." "default_value"
#Add_Option_List "l" "list" "Enter a colon-separated list of..." "foo:bar"
Parse_Options "$@"

Parse_Conf CVS.conf 

### Operation #################################################################

#Uncomment this if the script is meant to be run with superuser privileges.
#Verify_Superuser

tmpDir=`Temporary_Dir`
cd $tmpDir
cvs -d "$recipeRepository" import -m "Create Recipe repo" "$recipeModuleBase" recipes initial
rmdir $tmpDir

