#!/bin/sh

### Changelog #################################################################

# 2005/10/08 - [calica] First version

### Imports ###################################################################

source ScriptFunctions
Import GoboLinux
Import OptionParser
Import String
Import CVSTranslate

### Options ###################################################################

scriptDescription="Test the CVS translate functions"
scriptCredits="Copyright (C) 2005 Released under the GNU GPL."
helpOnNoArguments=yes
scriptUsage="<options> <recipe_tarballs>"
#scriptExample="-b -e entry_value File1"
#scriptNotes="<recipe> can be directory or tarball"
#Add_Option_Boolean "b" "bool" "A boolean option."
#Add_Option_Entry "e" "entry" "Specify <entry>." "default_value"
#Add_Option_List "l" "list" "Enter a colon-separated list of..." "foo:bar"
Parse_Options "$@"
shift $parsedArguments

Parse_Conf CVS.conf 

### Functions #################################################################

function tarball_into_cvs {
    Parameters "$@" recipe_tarball

    noext=`basename "$recipe_tarball"`
    for extension in ".gz" ".bz2" ".zip" ".tgz" ".tbz" ".tar"
    do
      noext=`basename "$noext" "$extension"`
    done

    recipename=`Get_Token    "$noext" "--" "0"`
    recipever=`Get_Token "$noext" "--" "1"`    

    releaseTag=`VersionRev_to_ReleaseTag $recipever $reciperev`

    newpair=`ReleaseTag_to_Pair $releaseTag`
    if [ "$recipever" != "$newpair" -a "$recipever" != "CVS" ]
    then
	echo "TEST FAILURE!!"
        echo "$recipename: $recipever"
        echo "ReleaseTag $releaseTag:    $newpair"
    fi
}

process_dir() {
    local dir="$1"

    ls "$dir" |grep "recipe.tar.bz2" | while read file
    do
        tarball_into_cvs $file
    done
}

### Operation #################################################################

#Uncomment this if the script is meant to be run with superuser privileges.
#Verify_Superuser

for tarball in "$@"
do
   [ -d "$tarball" ] && process_dir "$tarball" # Schmuck passed a directory!
   tarball_into_cvs $tarball
   : # stuff to do
done
