.\"This man page was created by Fibo, assistant to Gobo. 
.Dd April 21, 2003
.Dt HIER 7
.Os GoboLinux
.Sh NAME
.Nm hier
.Nd layout of file systems

.Sh DESCRIPTION
A sketch of the file system hierarchy. 



\" --------------- / directory --------------- 
.Bl -tag -width "/Programs/"
.It Pa /
root directory of the file system

\" --------------- /Depot directory --------------- 
.It Pa /Depot/
repository for users' files. This repository is meant to be organized as the user sees fit. 
No subdirectories of 
.Em "/Depot"
are considered part of the standard GoboLinux hierarchy.


\" --------------- /Files directory --------------- 
.It Pa /Files/
.Pp
.Bl -tag -width "Documentation/" -compact
.It Pa Codecs/
codecs used by multimedia players


\" --------------- /Files/Documentation directory --------------- 
.It Pa Documentation/
.Pp
.Bl -tag -width "Linux-mini-HOWTOs/" -compact
.It Pa Linux-HOWTOs/
detailed
.Em how to
documents on specific subjects
.It Pa Linux-mini-HOWTOs/
detailed
.Em mini how to
documents on specific subjects
.El

\" --------------- /Files/Fonts directory --------------- 
.It Pa Fonts/
.Pp
.Bl -tag -width "Ghostscript/" -compact
.It Pa 100dpi/
100 dpi fonts
.It Pa 75dpi/
75 dpi fonts
.It Pa Cyrillic/
cyrillic fonts
.It Pa Ghostscript/
ghostscript fonts
.It Pa Misc/
character-cell fonts, cursor fonts and other low-resolution fonts
.It Pa OTF/
OpenType fonts
.It Pa Speedo/
Speedo fonts
.It Pa TrueType/
TrueType fonts
.It Pa Type1/
Type 1 fonts. If font metric files are available, they must be placed here as well
.El

\" --------------- back to /Files directory --------------- 
.It Pa Plugins/
plugins, such as the ones needed by browsers
.El


\" --------------- /Mount directory --------------- 
.It Pa /Mount/
mounting point for additional local or remote filesystems
.Pp
.Bl -tag -width "Floppy/" -compact
.It Pa CD-ROM/
.It Pa Floppy/
.It Pa Zip/
.El


\" --------------- /Programs directory --------------- 
.It Pa /Programs/
contains a subdirectory for each installed program. Each of those subdirectories has, on its turn, 
a subdirectory for each version of the specific program, and a link labeled 
.Em Current 
pointing to the currently used version. Each program also has a 
.Em Settings 
directory storing the program's configuration files (which would be normally stored at 
.Em /etc
). This directory is unique for all versions of the program. Each program version may have a
.Em Resources
directory storing program metadata such as dependencies and environment variables.


\" --------------- /System directory --------------- 
.It Pa /System/
.Pp
.Bl -tag -width "Executables/" -compact

\" --------------- /System/Kernel directory --------------- 
.It Pa Kernel/
.Pp
.Bl -tag -width "Devices/" -compact
.It Pa Boot/
programs and configuration files used during operating system bootstrap
.It Pa Devices/
device files (managed by the 
.Em "dev filesystem"
).
.It Pa Modules/
contains the various kernel modules, organized by the kernel release
.It Pa Objects/
provides a view of the kernel's device tree (introduced with linux-2.6' 
.Em "sysfs filesystem"
)
.It Pa Status/
kernel status files (managed by the
.Em "proc filesystem"
).
.El

\" --------------- /System/Links directory --------------- 
.It Pa Links/
.Pp
.Bl -tag -width "Executables/" -compact
.It Pa Daemons/
this directory is managed by the runit tool, which supervises the
system daemons. Each entry in this directory corresponds to
a daemon, which can be brought up or down using 
.Em "runsvctrl",
or verified with 
.Em "runsvstat".
.It Pa Environment/
links to environment files. These are compiled into a 
.Em "Cache"
file and loaded by the shell, allowing programs to register their own
environment variables.
.It Pa Executables/
contains links to files from the programs'
.Em "bin"
and
.Em "sbin"
directories
.It Pa Headers/
this directory contains links to files from the programs'
.Em "include"
directories
.It Pa Libraries/
links to files from the programs'
.Em "lib"
directories

\" --------------- /System/Links/Manuals directory --------------- 
.It Pa Manuals/
.Pp
.Bl -tag -width "man{1-9}/" -compact
.It Pa info/
links to files from the programs'
.Em "info"
directories
.It Pa man{1-9}/
links to files from the programs'
.Em "man{1-9}"
directories
.El
.It Pa Shared/
links to files from the programs'
.Em "share"
directories
.El

\" --------------- /System/Settings directory --------------- 
.It Pa Settings/
configuration files and links to files from
.Em "Settings"
directory
.Pp
.Bl -tag -width "BootScripts/" -compact
.It Pa BootScripts/
scripts used during system boot. Actually, this is a symlink to
.Em "Settings/BootScripts/" 
on 
.Em "/Programs/BootScripts"
.El

\" --------------- back to /System directory --------------- 
.It Pa Variable/
multi-purpose log, temporary, transient and spool files
.Pp
.Bl -tag -width "tmp/" -compact
.It Pa tmp/
temporary files
.El
.El


\" --------------- /Users directory --------------- 
.It Pa Users/
personal areas for users
.El


.Sh NOTES
Compatibility with the UNIX legacy is obtained through creation of extra links not 
present in the tree shown above, such as:
.Bl -compact
.It
.Em ""
.It
.Em "/bin  -> /System/Links/Executables,"
.It
.Em "/dev  -> /System/Status,"
.It
.Em "/etc  -> /System/Settings,"
.It
.Em "/lib  -> /System/Links/Libraries,"
.It
.Em "/proc -> /System/Status,"
.It
.Em "/sbin -> /System/Links/Executables,"
.It
.EM "/sys  -> /System/Kernel/Objects,"
.It
.Em "/tmp  -> /System/Variable/tmp,"
and
.It
.Em "/var  -> /System/Variable,"
.It
.Em ""
.El
mirroring the GoboLinux tree into the UNIX tree. These symbolic links and the
.Em "/usr"
directory are gracefully handled by 
.Xr gobohide 8
.

.Sh "SEE ALSO"
gobohide(8), runint(8).
