#!/bin/sh

case "$1" in
    [sS]tart)
        option="-h"
        ;;
    [sS]top)
        option="-u"
        ;;
    *)
        echo "Usage: $0 <start|stop>"
        exit 1
esac
        
for dir in /bin /etc /lib /sbin /tmp /var /usr /proc /dev /sys /srv /mnt /media /lost+found /boot /home /root /linuxrc /initrd
do
    if [ -d "$dir" -o -h "$dir" ]
    then
        gobohide "$option" "$dir"
    fi
done
