all:
	gcc -o SuperUserName SuperUserName.c
	gcc -o IsExecutable IsExecutable.c
	mv SuperUserName IsExecutable ../bin/ 
static:	
	gcc -o SuperUserName SuperUserName.c -static
	gcc -o IsExecutable IsExecutable.c -static
	mv SuperUserName IsExecutable ../bin/ 
