#!/bin/bash (source)

export logMode="Normal"
export logLevel=${logLevelNormal}

eval "exec $questionFD<&2"
eval "exec $verboseFD<&2"
eval "exec $normalFD<&2"
eval "exec $terseFD<&2"
eval "exec $errorFD<&2"
eval "exec $debugFD>/dev/null"
eval "exec $logFD>/dev/null"
