#!/bin/bash (source)

export logMode="Verbose"
export logLevel=${logLevelVerbose}
eval "exec $questionFD>&-"
eval "exec $verboseFD>&-"
eval "exec $normalFD>&-"
eval "exec $terseFD>&-"
eval "exec $errorFD>&-"
eval "exec $debugFD>&-"
eval "exec $logFD>&-"

eval "exec $questionFD<&2"
eval "exec $verboseFD<&2"
eval "exec $normalFD<&2"
eval "exec $terseFD<&2"
eval "exec $errorFD<&2"
eval "exec $debugFD>/dev/null"
eval "exec $logFD>/dev/null"
