#!/bin/sh (source)

SIZE=$(stty size 2> /dev/null)
COLUMNS=${SIZE##* }
ROWS=${SIZE%% *}

colorGray="\033[1;30m"
colorBoldBlue="\033[1;34m"
colorBrown="\033[33m"
colorYellow="\033[1;33m"
colorBoldGreen="\033[1;32m"
colorBoldRed="\033[1;31m"
colorCyan="\033[36m"
colorBoldCyan="\033[1;36m"
colorRedWhite="\033[41;37m"
colorNormal="\033[0m"
colorBold="${colorYellow}"
colorOff="${colorNormal}"
