#!/bin/sh

Import File

##################################################
# Setting up variables
##################################################

if [ "$compileRecipeDir" ]
then
   compileRecipeDirs=("$compileRecipeDir" "${compileRecipeDirs[@]}")
fi

if [ -z "$compileRecipeDir" ]
then
   compileRecipeDir="${compileRecipeDirs[0]}"
fi

compileSupportedArchitectures=("i686" "ppc" "arm")
##################################################
# Helper functions
##################################################

function Check_Dir_Variable() {
   var="$1"
   eval [ "\$$var" ] || Die "Variable \\\$$var is not set. Please update your Compile.conf."
   eval Assert_Dir "\$$var"
}

function Assert_Dir() {
   local dir=$1
   if ! Is_Directory "$dir"
   then
      mkdir -p "$dir" || \
      $sudo mkdir -p "$dir"
      if [ "$?" != "0" ]
      then
         Die "Unable to create $dir"
      fi
   fi
}

function foreach_if_array_set() {
   local array=$1
   local cmd=$2
   eval "
      if [ \"\${$array[*]}\" ]
      then
         for item in \"\${$array[@]}\"
         do
            $cmd
         done
      fi
   "
}

function merge_array() {
   local array=$1
   foreach_if_array_set "$array" '
      echo -n "$item "
   '
}

function is_function_set() {
   [ "`type -t $1`" = "function" ]
}

### Future Scripts functions... ###

function Get_Size() {
   Parameters "$@" file
   ls -l "$file" | awk '{print $5}'
}

function Get_MD5() {
   Parameters "$@" file
   md5sum "$file" | awk '{print $1}'
}
